### ISSUE TITLE
Look into Bot spawning multiple instances.

### ISSUE THREAD

**Issue by wardellbagby** [wardellchandler/HangoutsBot#12]
Seems to happen when the Bot is running on a Windows computer and that computer goes to sleep or awakes from hibernation.

**Comment by cntrlwiz** [comment]
A little new data for you...my bot has apparently spawned a second instance.  Here's the interesting part:  It's running on a WS2012r2 server that doesn't sleep or hibernate.  Also, I haven't been home, so I'm pretty sure there has been no human interaction with the server.  It's running it a Git Bash window.  There is no auto-start or anything else that might spawn a second instance.

**Comment by wardellbagby** [comment]
Very very interesting. I get the feeling this is going to be incredibly tough to lock down.

**Comment by cntrlwiz** [comment]
I got home tonight and got the following from the console window:
( "..." = lines removed for clarity or privacy.  This bot is in 5 conversations.)

It's apparent that the re-connection following the exceptions created a second instance.

Hope this helps.

``` python
$ python main.py
Already up-to-date.
Connected!
WARNING:root:Adding fallback User: <hangups.user.User object at 0x03B90DD0>
...
WARNING:root:Adding fallback User: <hangups.user.User object at 0x043946D0>
Conversations:
...
WARNING:hangups.channel:Long-polling request failed: Request connection error: B
roken chunked payload.
Connection lost!
WARNING:hangups.channel:Long-polling request failed: Request connection error: B
roken chunked payload.
Connection lost!
WARNING:hangups.channel:Long-polling request failed: SID became invalid
Client unexpectedly disconnected:
[WinError 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "c:\dev\projects\ingbot\hangoutsbot\Core\Bot.py", line 149, in run
    loop.run_until_complete(self._client.connect())
  File "c:\dev\Python34\lib\asyncio\base_events.py", line 268, in run_until_comp
lete
    return future.result()
  File "c:\dev\Python34\lib\asyncio\futures.py", line 277, in result
    raise self._exception
  File "c:\dev\Python34\lib\asyncio\tasks.py", line 232, in _step
    result = coro.throw(exc)
  File "c:\dev\Python34\lib\site-packages\hangups\client.py", line 116, in conne
ct
    yield from self._listen_future
  File "c:\dev\Python34\lib\asyncio\futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "c:\dev\Python34\lib\asyncio\tasks.py", line 285, in _wakeup
    value = future.result()
  File "c:\dev\Python34\lib\asyncio\futures.py", line 277, in result
    raise self._exception
  File "c:\dev\Python34\lib\asyncio\tasks.py", line 236, in _step
    result = next(coro)
  File "c:\dev\Python34\lib\site-packages\hangups\channel.py", line 204, in list
en
    yield from self._longpoll_request()
  File "c:\dev\Python34\lib\site-packages\hangups\channel.py", line 337, in _lon
gpoll_request
    res.content.read(MAX_READ_BYTES), PUSH_TIMEOUT
  File "c:\dev\Python34\lib\asyncio\tasks.py", line 371, in wait_for
    return fut.result()
  File "c:\dev\Python34\lib\asyncio\futures.py", line 277, in result
    raise self._exception
  File "c:\dev\Python34\lib\asyncio\tasks.py", line 232, in _step
    result = coro.throw(exc)
  File "c:\dev\Python34\lib\site-packages\aiohttp\streams.py", line 274, in read

    return (yield from super().read(n))
  File "c:\dev\Python34\lib\site-packages\aiohttp\streams.py", line 186, in read

    yield from self._waiter
  File "c:\dev\Python34\lib\asyncio\futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "c:\dev\Python34\lib\asyncio\tasks.py", line 285, in _wakeup
    value = future.result()
  File "c:\dev\Python34\lib\asyncio\futures.py", line 277, in result
    raise self._exception
  File "c:\dev\Python34\lib\asyncio\selector_events.py", line 825, in _read_read
y
    data = self._sock.recv(self.max_size)
  File "c:\dev\Python34\lib\ssl.py", line 731, in recv
    return self.read(buflen)
  File "c:\dev\Python34\lib\ssl.py", line 620, in read
    v = self._sslobj.read(len or 1024)
ConnectionResetError: [WinError 10054] An existing connection was forcibly close
d by the remote host

Waiting 5 seconds...
Trying to connect again (try 1 of 5)...
Connected!
WARNING:root:Adding fallback User: <hangups.user.User object at 0x03BD6EF0>
...
WARNING:root:Adding fallback User: <hangups.user.User object at 0x04E412B0>
Conversations:
...
```

**Comment by wardellbagby** [comment]
Was the bot still actively running?

**Comment by cntrlwiz** [comment]
Yes, and providing 2 responses for each command.

**Comment by endofline** [comment]
experimenting with a temporary workaround for duplicated event ids in our forked copy of the bot's `on_event` handler @ https://github.com/nylonee/hangupsbot/commit/9fd7eace768631598c207a3ac2d4d6d5c5329959 - perhaps this will be of some use
