### ISSUE TITLE
Cleverbot TypeError when responding to bots name

### ISSUE THREAD

**Issue by SeeJayEmm** [wardellchandler/HangoutsBot#28]
When I reference the bot by name in chat the following error is thrown when it responds. A response is successfully returned in chat.

This appears in both one-on-one chat and group hangouts.

asyncio (3.4.3) if it matters.

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<think() done, defined at /home/chris/HangoutsBot/Core/Commands/DefaultCommands.py:25> exception=TypeError("'NoneType' object is not iterable",)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/home/chris/HangoutsBot/Core/Commands/DefaultCommands.py", line 28, in think
    yield from bot.send_message(event.conv, clever_session.think(' '.join(args)))
TypeError: 'NoneType' object is not iterable
```

**Comment by wardellbagby** [comment]
This is fixed on my local version, haven't pushed it yet.
