### ISSUE TITLE
Invalid Escape

### ISSUE THREAD

**Issue by djeraseit** [wardellchandler/HangoutsBot#32]
Can someone please make sense of this to me?

root@omega:/media/windows/HangoutsBot# python3 Main.py
Already up-to-date.
Traceback (most recent call last):
  File "Main.py", line 41, in <module>
    HangoutsBot("Core" + os.sep + "cookies.txt", "Core" + os.sep + "config.json", command_char='/').run()
  File "/media/windows/HangoutsBot/Core/Bot.py", line 68, in **init**
    self.config = ConfigDict.ConfigDict(config_path)
  File "/media/windows/HangoutsBot/Core/Util/ConfigDict.py", line 11, in **init**
    self.load()
  File "/media/windows/HangoutsBot/Core/Util/ConfigDict.py", line 16, in load
    self.config = json.loads(open(self.filename, encoding='utf-8').read(), encoding='utf-8')
  File "/usr/lib/python3.4/json/**init**.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 5 column 11 (char 87)

**Comment by cntrlwiz** [comment]
You have probably nerfed up your json.config file...JSON structure is very strict, and there is no error-handling for the decoder routine.  Take a look at line 5, col 11 of your config.json.
