### ISSUE TITLE
issue w/ 8080?

### ISSUE THREAD

**Issue by polarizeme** [wardellchandler/HangoutsBot#37]
I'm not really sure what's going on, to be honest. Ha.

I'm using HangoutsBot and hangups.

When running the hangups adapter I was getting no response from the bot, so I decided to just run HangoutsBot (Main.py) and see if there were any errors occurring.

When I run Main.py, things start off just fine:

```
You're logged in!
[05/Jun/2015:20:33:01] ENGINE Listening for SIGTERM.
[05/Jun/2015:20:33:01] ENGINE Listening for SIGUSR1.
[05/Jun/2015:20:33:01] ENGINE Listening for SIGHUP.
[05/Jun/2015:20:33:01] ENGINE Bus STARTING
[05/Jun/2015:20:33:01] ENGINE Started monitor thread 'Autoreloader'.
[05/Jun/2015:20:33:01] ENGINE Started monitor thread '_TimeoutMonitor'.
[05/Jun/2015:20:33:01] ENGINE Serving on http://127.0.0.1:8081
[05/Jun/2015:20:33:01] ENGINE Bus STARTED
Connected!
```

But the second I try anything like /ping or /help, I get this:

```
Conversation ID: [redacted]
Conversation name: [redacted]
User ID: UserID(chat_id='[redacted]', gaia_id='[redacted]')
User name: [redacted]
Timestamp: 2015-06-05 20:40:04
Text: /ping

Future/Task exception was never retrieved
future: Task(<handle>)<exception=ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /receive/engineering (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)",),)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 493, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 291, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 841, in send
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 106, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 90, in _new_conn
    (self.host, self.port), self.timeout, *extra_args)
  File "/usr/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 327, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 543, in urlopen
    raise MaxRetryError(self, url, e)
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /receive/engineering (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 302, in _step
    result = next(coro)
  File "/home/ubuntu/meatwad/node_modules/hubot-hangups/HangoutsBot/handlers.py", line 25, in handle
    yield from self.handle_command(event)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 84, in coro
    res = func(*args, **kw)
  File "/home/ubuntu/meatwad/node_modules/hubot-hangups/HangoutsBot/handlers.py", line 37, in handle_command
    requests.post(url, data=payload)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /receive/engineering (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)
```

After poking around a bit, it seems like HangoutsBot isn't even listening on 8080 (nothing is). It's listening on 8081 just fine.

How do I get HangoutsBot to actually listen on 8080 as well as 8081?

Cheers!

**Comment by wardellbagby** [comment]
Sorry bud, I don't know anything about the [hubot-hangups adapter.](https://github.com/groupby/hubot-hangups/) You're going to want to talk to @groupby, as this seems to be an issue with his own project.

**Comment by polarizeme** [comment]
The problem recounted above, including the error output, was when running Main.py from HangoutsBot outside of running hangups.

**Comment by wardellbagby** [comment]
The [hubot-hangups adapter](https://github.com/groupby/hubot-hangups/) uses a modified version of an old release of my HangoutsBot. If you look at this stack trace here, the error is occurring in the at line 37 of the handlers.py file, where it seems like their version of the HangoutsBot is attempting to connect to a local server running on port 8080. My HangoutsBot doesn't do that and has never done that. I believe that they use a local server for their hubot integration, but as I said before, you're going to want to talk to @groupby, because the issue lies with his modified HangoutsBot and not mine.

**Comment by polarizeme** [comment]
Ahhhh. I didn't know hangups was using an older, modified version. I assumed his hangups versions were pulling in the latest HangoutsBot changes as well. I'll hit him up. Also, apologies if the shortness in my last comment seemed abrasive. Typing on my phone while multitasking. ;]

Cheers!
