### ISSUE TITLE
missing 1 required position argument: 'initial_data'

### ISSUE THREAD

**Issue by drwahl** [wardellchandler/HangoutsBot#42]
I'm running a hubot-hangups process inside a docker container.  When it launches, I get the following error from HangoutsBot:

```
root@10b2517f23d3:/opt/hubot# bin/hubot -a hangups
Python path is python3
checkInstall script python3 /opt/hubot/node_modules/hubot-hangups/checkInstall.py
result {"stdout":"","stderr":"","status":0}
You're logged in!
Client unexpectedly disconnected:
_on_connect() missing 1 required positional argument: 'initial_data'
Traceback (most recent call last):
  File "/opt/hubot/node_modules/hubot-hangups/HangoutsBot/hangupsbot.py", line 137, in run
    loop.run_until_complete(self._client.connect())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 102, in connect
    yield from self._listen_future
  File "/usr/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 209, in listen
    yield from self._longpoll_request()
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 338, in _longpoll_request
    yield from self._on_push_data(chunk)
  File "/usr/local/lib/python3.4/dist-packages/hangups/channel.py", line 359, in _on_push_data
    yield from self.on_connect.fire()
  File "/usr/local/lib/python3.4/dist-packages/hangups/event.py", line 50, in fire
    yield from gen
  File "/usr/local/lib/python3.4/dist-packages/hangups/event.py", line 48, in fire
    gen = observer(*args, **kwargs)
TypeError: _on_connect() missing 1 required positional argument: 'initial_data'
```

Not sure what I'm doing wrong exactly.  Is the hubot-hangups adapter calling HangoutsBot incorrectly?  Or is this a bug in HangoutsBot?

**Comment by wardellbagby** [comment]
Assuming you're talking about https://github.com/groupby/hubot-hangups/ here...

So, that project isn't being actively maintained anymore, (well, neither is this one to be honest) and the issue lies with them, not with HangoutsBot here.

That being said, if you downgrade your hangups package to 0.2.9, it should work fine.

**Comment by drwahl** [comment]
I've found a workaround in that i'm using hangupsjs instead.  Thanks for taking time to respond, even though it wasn't an issue with HangoutsBot.

**Comment by jusplainmike** [comment]
Sorry to resurrect this but I couldn't find an email address for your drwahl. I was wondering on your workaround using hangupsjs. Would you email me jusplainmike@gmail.com?

**Comment by wardellbagby** [comment]
@jusplainmike It was very likely downgrading hangups to 0.2.9.

**Comment by drwahl** [comment]
I've stopped using this module and have started using hubot-hangupsjs.
